---
name: 'Deploy2'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/action.yml@main
      with:
        name: OctoCat
