---
name: 'Deploy2'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: korniyana/qwerty/.github/actions/hello
      with:
        name: OctoCat
