name: Call a reusable workflow

on:
  workflow_dispatch:
      
env:
  GIT_BRANCH: ""

jobs:
  call-workflow-passing-data1:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
    - name: Extract branch name ${{env.GIT_BRANCH}}
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
  call-workflow-passing-data:
    needs: call-workflow-passing-data1
    uses: korniyana/qwerty/.github/workflows/workflow-B.yml@{{env.GIT_BRANCH}}
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}

