---
name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      env_name: #https://github.community/t/can-workflow-dispatch-input-be-option-list/127338/2 no options list yet
        description: 'Environment name (possible values are: tz, tz2, tz3, tz4, sz, prod)'
        required: true
        default: tz
      
env:
  GIT_BRANCH: ""

jobs:
  call-workflow-passing-data1:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> "$GITHUB_ENV"
    - name: Show
      run: echo ${{env.GIT_BRANCH}}
  call-workflow-passing-data:
    needs: call-workflow-passing-data1
    uses: korniyana/qwerty/.github/workflows/workflow-B.yml@master
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}

