name: Call a reusable workflow

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: korniyana/qwerty/.github/workflows/workflow-B.yml@master
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
