---
name: 'Deploy2'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: qwerty/.github/actions/hello@latest
      with:
        name: OctoCat
